### ISSUE TITLE
Main App functionality

### ISSUE THREAD

**Issue by ngiachou** [elpaxoudis/WalletHero#14]
The main app will consist of three modes which depend on the opening time of the app.
The main app will be a terminal app for now. Later we will implement the GUI staff.

For the first time the app is launched, the following should happen in terminal:
1. Ask for a user name (this is not needed as a login credentials)
2. Announce the current month
3. Ask for the current month's expenses target

Example run:
```
Please tell us your name: Nikos
The current month is December.
Please tell us your expenses target for December: 200
```

If the app is launched for the first time in a month, the following should happen in terminal:
1. Announce the current month
2. Ask for the current month's expenses target

Example run:
```
The current month is December.
Please tell us your expenses target for December: 200
```

For any other case a main menu will be shown.

1. Input cost
2. Statistics
    1. Show costs per month
    2. Show costs per month per day
    3. Show costs per month per cost category
    4. Show costs per month per day per cost category

where the statistics option has sub-options.

Example run:
```
1. Input cost
2. Statistics
(please choose 1 or 2): 2
Statistics menu is chosen
1. Show costs per month
2. Show costs per month per day
3. Show costs per month per cost category
4. Show costs per month per day per cost category
```

**Comment by ngiachou** [comment]
> Test comment from slack.
<sub>[View in Slack](https://pysquad-workspace.slack.com/archives/GE1GBHG77/p1544376547000900)</sub>

**Comment by kpaxiotis** [comment]
The main app functionality looks good to me. My only suggestion is that we should add an extra option that exits the program at every stage of the app.

**Comment by ngiachou** [comment]
By exit you mean closing the app or more like a go-back functionality?

**Comment by pagidas** [comment]
- Maybe a `clearScreen()` which so info that's not needed won't be printed on the console (example: previous messages)

- I think **Exit** option should exist in every Menu and sub-menu. But **Go back** only in Sub-menus. For early development we should just implement the **Exit** option which terminates the app, and the **Go back** can just go to the Main Menu

**Comment by ngiachou** [comment]
@pagidas maybe we should open a new PR for your comments on Dec 15, 2018?

**Comment by pagidas** [comment]
I see that part of the issue has been solved. But not all, am I right? So I suppose you mean open a new PR to solve and probably close the issue. If so, then do it

**Comment by ngiachou** [comment]
>     * Maybe a `clearScreen()` which so info that's not needed won't be printed on the console (example: previous messages)
> 
>     * I think **Exit** option should exist in every Menu and sub-menu. But **Go back** only in Sub-menus. For early development we should just implement the **Exit** option which terminates the app, and the **Go back** can just go to the Main Menu

I was referring to this comment, but as I see those features are also implemented.

Nevertheless, we should keep this issue open, since a lot more functionality is to be implemented. We can observe that from the numerous TODO comments throughout `mainApp.py`.

**Comment by ngiachou** [comment]
Closing. This issue is totally out of context because we don't have any console functionality now.
