### ISSUE TITLE
Decluttering project structure

### ISSUE THREAD

**Issue by pagidas** [elpaxoudis/WalletHero#35]
We have changed plans on how we're implementing the application, and maybe some of the old code is very out of context. However that doesn't mean that we delete forever those ideas. We could keep some of these files locally so we discuss them in another feature.

But right now it is trivial that we have a clear workspace -- the folder application structure. I suggest we delete ***cost_management*** folder and the ***mainApp.py*** file.

In order to do this, @elpaxoudis I need your permission and your thought on this since most of those ideas were yours.
- Can I delete the files I mentioned above?
- If so... tell me *ONLY* when you saved the ones you'd want for future features

Last but not least we should remove one of the **.gitignore** files. There is one on the root of the whole project and one on the root of the **wh-ionic** project

**Comment by pagidas** [comment]
@elpaxoudis Whenever you're ready, answer me in a comment in this issue so we can take this further. ***QuickEdit:*** I made the fixes in a separate branch locally, and I wait for your review

**Comment by ngiachou** [comment]
Closing since the branch related is merged successfully.
