### ISSUE TITLE
Decluttering issue board

### ISSUE THREAD

**Issue by pagidas** [elpaxoudis/WalletHero#36]
I check the issue board to see if we are on the right track on things we want to implement, or thoughts on the project, and I have to to say that these issues that are out of context confuse me.

I suggest we should close, remove or whatever those that are not in our thought process. That will only make the issue board better.

Again, @elpaxoudis some of those issues were thoughts of yours. So put your thoughts on comment on which ones we might need to keep :)

**Comment by ngiachou** [comment]
Ok, I'm on it!

**Comment by ngiachou** [comment]
I think this issue is solved now. If need be, I'll reopen it in the future.
